In [5]:
import pandas as pd

df = pd.read_csv('halloween_vendas.csv')

df.head(3)

,pedido_id,data_venda,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega
0,844,2025-11-21 18:02:35,Fantasia de vampiro,Fantasia,Loja física,Curitiba,3,132.5,72.08,15,Cancelado,Adulto,G,NaN
1,378,2024-10-29 18:41:26,Fantasia de bruxa,FANTASIA!!!,Loja física,Maringá,3,110.0,57.00,5,Concluído,Adulto,M,2024-11-03 18:41:26
2,953,2025-09-05 21:16:09,Fantasia de bruxa,Fantasia,Web,Maringá,2,116.6,60.42,5,Concluído,Adulto,M,2025-09-10 21:16:09

In [6]:
print("Total de linhas e colunas:", df.shape)

Total de linhas e colunas: (1500, 14)

In [ ]:
import re

def limpar_categoria(texto):
    if pd.isna(texto) or str(texto).strip() == '':
        return 'sem categoria'
    
    limpo = str(texto).strip().lower()
    
    limpo = re.sub(r'[^a-záéíóúâêîôûãõç\s]', '', limpo).strip()
    
    if limpo == '':
        return 'sem categoria'
        
    return limpo

In [10]:

df['categoria'] = df['categoria'].apply(limpar_categoria)

df.head(3)

,pedido_id,data_venda,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega
0,844,2025-11-21 18:02:35,Fantasia de vampiro,fantasia,Loja física,Curitiba,3,132.5,72.08,15,Cancelado,Adulto,G,NaN
1,378,2024-10-29 18:41:26,Fantasia de bruxa,fantasia,Loja física,Maringá,3,110.0,57.00,5,Concluído,Adulto,M,2024-11-03 18:41:26
2,953,2025-09-05 21:16:09,Fantasia de bruxa,fantasia,Web,Maringá,2,116.6,60.42,5,Concluído,Adulto,M,2025-09-10 21:16:09

In [ ]:
def padronizar_canal(canal):
    c = str(canal).strip().lower()
    if 'mercado' in c:
        return 'Mercado'
    elif 'loja' in c or 'física' in c or 'fisica' in c:
        return 'Loja física'
    elif 'web' in c:
        return 'Web'
    return canal

df['canal_venda'] = df['canal_venda'].apply(padronizar_canal)

print("Canais de venda padronizados com sucesso!")

Canais de venda padronizados com sucesso!

In [11]:
print("--- DISTRIBUIÇÃO DAS CATEGORIAS ---")
print(df['categoria'].value_counts())

print("\n--- DISTRIBUIÇÃO DOS CANAIS DE VENDA ---")
print(df['canal_venda'].value_counts())

--- DISTRIBUIÇÃO DAS CATEGORIAS ---
categoria
fantasia         979
acessorio        503
sem categoria     18
Name: count, dtype: int64

--- DISTRIBUIÇÃO DOS CANAIS DE VENDA ---
canal_venda
Web            666
Loja física    551
Mercado        283
Name: count, dtype: int64